### ISSUE TITLE
Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification) - AccessDenied

### ISSUE THREAD

**Issue by indydk** [LFM8787/PSADT.ToastNotification#2]
Hey

Great work - but I get the following error: (when showing ToastNotification)

Error Record:
-------------

Message        : Exception calling "Show" with "1" argument(s): "Adgang nægtet. (Undtagelse fra HRESULT: 0x80070005 (E_
                 ACCESSDENIED))"
InnerException : System.UnauthorizedAccessException: Adgang nægtet. (Undtagelse fra HRESULT: 0x80070005 (E_ACCESSDENIED
                 ))
                    ved Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification)
                    ved CallSite.Target(Closure , CallSite , Object , Object )

FullyQualifiedErrorId : UnauthorizedAccessException
ScriptStackTrace      : at <ScriptBlock>, C:\PSAppDeployToolkit_v3.9.2\Toolkit\AppDeployToolkit\PSADT.ToastNotification
                        \ToastNotificationExtension.ps1: line 2190
                        at Show-BalloonTip<Process>, C:\PSAppDeployToolkit_v3.9.2\Toolkit\AppDeployToolkit\PSADT.ToastN
                        otification\ToastNotificationExtension.ps1: line 2236
                        at <ScriptBlock>, <No file>: line 131
                        at Exit-Script, C:\PSAppDeployToolkit_v3.9.2\Toolkit\AppDeployToolkit\PSADT.ToastNotification\T
                        oastNotificationExtension.ps1: line 623
                        at <ScriptBlock>, C:\PSAppDeployToolkit_v3.9.2\Toolkit\Deploy-Application.ps1: line 312
                        at <ScriptBlock>, <No file>: line 1
                        at <ScriptBlock>, <No file>: line 1

PositionMessage : At C:\PSAppDeployToolkit_v3.9.2\Toolkit\AppDeployToolkit\PSADT.ToastNotification\ToastNotificationExt
                  ension.ps1:2190 char:6
                  + ...             $null = [Windows.UI.Notifications.ToastNotificationManage ...
                  +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error Inner Exception(s):
-------------------------

Message        : Adgang nægtet. (Undtagelse fra HRESULT: 0x80070005 (E_ACCESSDENIED))
InnerException :

**Comment by LFM8787** [comment]
Hi there, I've never received that error in my test and environments:

1. Other toast notifications are shown normally?
2. The "original" toast notification that comes with PSADT 3.9.2 is shown (by PowerShell AppID) normally?
3. Can you test this Microsoft app in your system: [Notification Visualizer](https://apps.microsoft.com/store/detail/notifications-visualizer/9NBLGGH5XSL1?hl=es-es&gl=es&rtc=1)

**Comment by indydk** [comment]
Hey

1. it seems to fall back to original function
2. Yes
3. Notification Visualizer is working

**Comment by LFM8787** [comment]
Enable `Toolkit_LogDebugMessage` in **AppDeployToolkitConfig** and send the log again please.

**Comment by indydk** [comment]
[PS_AppDeployToolkitMain_3.9.2_EN_01_PSAppDeployToolkit_Install.log](https://github.com/LFM8787/PSADT.ToastNotification/files/10732593/PS_AppDeployToolkitMain_3.9.2_EN_01_PSAppDeployToolkit_Install.log)

**Comment by Camell2** [comment]
I'm having the exact same problem. Error 0x80070005 whene running through SCCM. No problems when running on a test non-domain-joined pc. Also running PSADT 3.9.2.

<![LOG[[Installation] :: Detected 64-bit OS Architecture]LOG]!><time="13:55:37.07760" date="02-14-2023" component="Deploy Application" context="NT AUTHORITY\SYSTEM" type="1" thread="10140" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Found C:\WINDOWS\ccmcache\69\Files\x64\ZoomInstallerFull.msi, now attempting to install the Install: Zoom Desktop Client (64-bit).]LOG]!><time="13:55:37.09360" date="02-14-2023" component="Deploy-Application" context="NT AUTHORITY\SYSTEM" type="1" thread="10140" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Displaying Installation Progress with message: Installerer Zoom Desktop Client (64-bit). Det tager kun et øjeblik. Vent venligst...]LOG]!><time="13:55:37.10260" date="02-14-2023" component="Show-InstallationProgress" context="NT AUTHORITY\SYSTEM" type="1" thread="10140" file="Deploy-Application.ps1">
<![LOG[[Installation] :: Unable to show Toast Notification. Falling back to original function...
Error Record:
-------------

Message        : Exception calling "Show" with "1" argument(s): "Adgang nægtet. (Undtagelse fra HRESULT: 0x80070005 (E_
                 ACCESSDENIED))"
InnerException : System.UnauthorizedAccessException: Adgang nægtet. (Undtagelse fra HRESULT: 0x80070005 (E_ACCESSDENIED
                 ))
                    ved Windows.UI.Notifications.ToastNotifier.Show(ToastNotification notification)
                    ved CallSite.Target(Closure , CallSite , Object , Object )

FullyQualifiedErrorId : UnauthorizedAccessException
ScriptStackTrace      : at <ScriptBlock>, C:\WINDOWS\ccmcache\69\AppDeployToolkit\PSADT.ToastNotification\ToastNotifica
                        tionExtension.ps1: line 4109
                        at Show-InstallationProgress<Process>, C:\WINDOWS\ccmcache\69\AppDeployToolkit\PSADT.ToastNotif
                        ication\ToastNotificationExtension.ps1: line 4190
                        at <ScriptBlock>, C:\WINDOWS\ccmcache\69\Deploy-Application.ps1: line 203
                        at <ScriptBlock>, <No file>: line 1
                        at <ScriptBlock>, <No file>: line 1

PositionMessage : At C:\WINDOWS\ccmcache\69\AppDeployToolkit\PSADT.ToastNotification\ToastNotificationExtension.ps1:410
                  9 char:6
                  + ...             $null = [Windows.UI.Notifications.ToastNotificationManage ...
                  +                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



Error Inner Exception(s):
-------------------------

Message        : Adgang nægtet. (Undtagelse fra HRESULT: 0x80070005 (E_ACCESSDENIED))
InnerException :

**Comment by indydk** [comment]
@Camell2 and @LFM8787 

I can confirm - it works on a workgroup computer.

**Comment by LFM8787** [comment]
I was unable to reproduce the error in my environment, I tested in a local domain joined computer, after SCCM task sequence via PXE and the Toast Notification is working as always.

Try raising the first Toast Notification as a user, instead SYSTEM, just execute the scrip as Administrator in Powershell ISE...

Is the application able to interact with the logged in user?

![image](https://user-images.githubusercontent.com/13755139/218996028-14dad206-e675-4ec5-8880-f42ae9674510.png)

**Comment by indydk** [comment]
Same problem :(

Running as administrator or in system context (in ISE or Powershell prompt)

**Comment by indydk** [comment]
Hey

![cut](https://user-images.githubusercontent.com/10740108/219307349-6d039aa0-e738-4cf8-9a04-940c549fbc97.JPG)

Shouldn't this part of the code be executed in the user's context? (it seems to be running in admin/system context)

**Comment by LFM8787** [comment]
> Hey
> 
> ![cut](https://user-images.githubusercontent.com/10740108/219307349-6d039aa0-e738-4cf8-9a04-940c549fbc97.JPG)
> 
> Shouldn't this part of the code be executed in the user's context? (it seems to be running in admin/system context)

No, it's intentional.

In my tests the showing of the Toast Notification is called by SYSTEM or any user and it's showed normally, even interactively with any user logged in.

I'm trying to reproduce the error to solve it.

**Comment by indydk** [comment]
Hey

Using the same method (burnttoast module) - same error.

![Udklip](https://user-images.githubusercontent.com/10740108/219331440-19b19212-95f4-4cf0-9c2a-c636bbc7f771.JPG)

Left side running as system - right side running as current user. 

https://github.com/Windos/BurntToast/issues/27

**Comment by LFM8787** [comment]
Can you test with [Process Monitor](https://learn.microsoft.com/en-us/sysinternals/downloads/procmon) what is blocking you when trying to raise the notification as SYSTEM?

**Comment by indydk** [comment]
I see no errors in Process Monitor :(

**Comment by Localuser0** [comment]
I have the exact same problem.

**Comment by LFM8787** [comment]
I managed to reproduce the error in my environment, will try to get to a fix, no ETA for now.

Try the following:
1. Create a SCCM application that runs as SYSTEM.
2. Deploy to machine.
3. Install as local Administrator, check if the Toast Notification works.

**Comment by indydk** [comment]
I'm not sure what you mean? (step 3.)

**Comment by Localuser0** [comment]
Hey @LFM8787 

Any ETA on a fix :)

**Comment by LFM8787** [comment]
Hi there, no ETA for the moment, but already fixed for the next version. I'm actually rewriting the complete extension, thousand of lines and another extension to fix other PSADT bugs.😎

**Comment by LFM8787** [comment]
Hey @Localuser0, @indydk and @Camell2 please test the latest v1.1 release.

**Comment by Localuser0** [comment]
Hey

I get this error:

`<![LOG[[Post-Installation] :: Executing function [Show-BalloonTip]. Text: Installation færdig.]LOG]!><time="07:49:52.006120" date="03-29-2023" component="Show-BalloonTip" context="NT AUTHORITY\SYSTEM" type="2" thread="2472" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: Converting the SID [S-1-5-32-545] to an NT Account name.]LOG]!><time="07:49:52.014120" date="03-29-2023" component="ConvertTo-NTAccountOrSID" context="NT AUTHORITY\SYSTEM" type="1" thread="2472" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: Setting permissions [Permissions:Read, InheritanceFlags:ContainerInherit, ObjectInherit, PropagationFlags:None, AccessControlType:Allow, Method:Add] on path [C:\WINDOWS\TEMP\PSAppDeployToolkit\psadttoastnotification\PS_AppDeployToolkitMain_392_EN_01] for user [BUILTIN\Brugere].]LOG]!><time="07:49:52.028120" date="03-29-2023" component="Set-ItemPermission" context="NT AUTHORITY\SYSTEM" type="1" thread="2472" file="Deploy-Application.ps1">
<![LOG[[Post-Installation] :: Unable to create Toast Notification template...
Error Record:
-------------

Message        : The variable cannot be validated because the value $null is not a valid value for the Path variable.
InnerException : 

FullyQualifiedErrorId : ValidateSetFailure
ScriptStackTrace      : at Get-IconFromFile<Process>, C:\PSAppDeployToolkit_v3.9.2\Toolkit\AppDeployToolkit\PSADT.DataE
                        xtraction\DataExtractionExtension.ps1: line 393
                        at <ScriptBlock>, C:\PSAppDeployToolkit_v3.9.2\Toolkit\AppDeployToolkit\PSADT.ToastNotification
                        \ToastNotificationExtension.ps1: line 2101
                        at <ScriptBlock>, C:\PSAppDeployToolkit_v3.9.2\Toolkit\AppDeployToolkit\PSADT.ToastNotification
                        \ToastNotificationExtension.ps1: line 409
                        at <ScriptBlock>, C:\PSAppDeployToolkit_v3.9.2\Toolkit\AppDeployToolkit\PSADT.ToastNotification
                        \ToastNotificationExtension.ps1: line 454
                        at Show-BalloonTip<Process>, C:\PSAppDeployToolkit_v3.9.2\Toolkit\AppDeployToolkit\PSADT.ToastN
                        otification\ToastNotificationExtension.ps1: line 2180
                        at Exit-Script, C:\PSAppDeployToolkit_v3.9.2\Toolkit\AppDeployToolkit\AppDeployToolkitMain.ps1:
                         line 1725
                        at <ScriptBlock>, C:\PSAppDeployToolkit_v3.9.2\Toolkit\Deploy-Application.ps1: line 307
                        at <ScriptBlock>, <No file>: line 1
                        at <ScriptBlock>, <No file>: line 1

PositionMessage : At C:\PSAppDeployToolkit_v3.9.2\Toolkit\AppDeployToolkit\PSADT.DataExtraction\DataExtractionExtension
                  .ps1:393 char:4
                  +             $Path = $envImageresLibraryPath
                  +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



]LOG]!><time="07:49:52.095120" date="03-29-2023" component="Show-BalloonTip" context="NT AUTHORITY\SYSTEM" type="3" thread="2472" file="Deploy-Application.ps1">`

**Comment by LFM8787** [comment]
Hi there @Localuser0 it seems to be a known bug in https://github.com/LFM8787/PSADT.DataExtraction

Please download the latest version (v1.0.1) and test again.

Also make sure you have the new required extension: https://github.com/LFM8787/PSADT.RunAsActiveUser

**Comment by Localuser0** [comment]
@LFM8787 Thanks for quick reply :)

It seems to be working now - but now images is shown in the toast notification. 

I have created the folder og added the images. 
![Udklip](https://user-images.githubusercontent.com/125663148/228506588-f8476791-4623-4f10-9311-1eec912f9518.JPG)
![Udklip](https://user-images.githubusercontent.com/125663148/228507115-6746f0fa-ee99-4eaa-8791-42953b6b9ba6.JPG)

**Comment by LFM8787** [comment]
@Localuser0 you have to extract the zip into toolkit folder, no need to create the SupportFiles one, it should be created when extracting.

Regarding the Show-InstallationProgress notification you can configure how to display the images and what to display, by default no Hero or App images are shown, check the xml configuration file.

Please provide consistent translation to your language for the next release :)
